// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZc4zF0X4UFRN84awwIgx7zPPyWot0I2g',
    appId: '1:380770719454:web:97a8db8b12a27da8d4944f',
    messagingSenderId: '380770719454',
    projectId: 'flutter-folder',
    authDomain: 'flutter-folder.firebaseapp.com',
    databaseURL: 'https://flutter-folder-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-folder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLpGgOwQnuSp0r72iZnXOmctbI57qjGpw',
    appId: '1:380770719454:android:ded02e432c42f3acd4944f',
    messagingSenderId: '380770719454',
    projectId: 'flutter-folder',
    databaseURL: 'https://flutter-folder-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-folder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6mT5EavZQBsPw8ciK2bXCU693J6uxEEE',
    appId: '1:380770719454:ios:b232e322121f1563d4944f',
    messagingSenderId: '380770719454',
    projectId: 'flutter-folder',
    databaseURL: 'https://flutter-folder-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-folder.appspot.com',
    iosBundleId: 'com.example.marketList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6mT5EavZQBsPw8ciK2bXCU693J6uxEEE',
    appId: '1:380770719454:ios:073ad85e6490e19fd4944f',
    messagingSenderId: '380770719454',
    projectId: 'flutter-folder',
    databaseURL: 'https://flutter-folder-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-folder.appspot.com',
    iosBundleId: 'com.example.marketList.RunnerTests',
  );
}
